import mongoose from "mongoose";

const EmployeeSchema = new mongoose.Schema(
  {
    // _id auto-generated by MongoDB
    first_name:      { type: String, required: true, trim: true },
    last_name:       { type: String, required: true, trim: true },
    email:           { type: String, required: true, trim: true, lowercase: true, unique: true },
    position:        { type: String, required: true, trim: true },
    salary:          { type: Number, required: true, min: 0 },
    date_of_joining: { type: Date, required: true },
    department:      { type: String, required: true, trim: true },
    profile_image_url:   { type: String, default: null }
  },
  {
    timestamps: { createdAt: "created_at", updatedAt: "updated_at" }
  }
);

export default mongoose.model("Employee", EmployeeSchema);